version: '3.8'

services:
  web:
    build:
      context: .
    container_name: flask-app
    ports:
      - "5000:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: python app.py
    restart: always
    environment:
      - FLASK_ENV=development